// Example sentences and synonyms are not generated by the app. When a word has none, the user is
// sent to Naver's English dictionary and pastes what they find (spec 7-3), so nothing has to be
// collected or generated on the app's side.
const NAVER_ENGLISH_DICTIONARY = 'https://en.dict.naver.com/#/search'

// examples open straight on the dictionary's example-sentence results; synonyms sit on the word's entry
const RANGE = {
  example: '&range=example',
  synonyms: '',
}

export function searchUrl(word, kind) {
  return `${NAVER_ENGLISH_DICTIONARY}?query=${encodeURIComponent(word)}${RANGE[kind]}`
}
